// elastic adaptive
export const SET_CURRENT_FONT_SIZE = 'SET_CURRENT_FONT_SIZE'
export const SET_USER_DEVICE_TYPE = 'SET_USER_DEVICE_TYPE'

// ui
export const SET_LANG = 'SET_LANG'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_GLOBAL_PADDING_TOP = 'SET_GLOBAL_PADDING_TOP'
export const SET_SLIDES_QUANTITY = 'SET_SLIDES_QUANTITY'
export const SET_SCROLLING_STATUS = 'SET_SCROLLING_STATUS'
export const SET_VISIBLE_BANNER = 'SET_VISIBLE_BANNER'
